### ISSUE TITLE
Search for homo naledi fails (v. 1.0.3)

### ISSUE THREAD

**Issue by pvanheus** [codeforscience/sciencefair#100]
With the eLife datasource enabled, search for "Homo naledi" fails. 

It should return papers such as DOI 10.7554/eLife.10627.

As discussed on IRC, this might be related to the title having `<italics>Homo naledia</italics>` markup.

**Comment by blahah** [comment]
Thanks for reporting this. As discussed, I think the tokeniser we run before indexing the documents is failing to strip the XML tags. Should be a simple fix (famous last words!).

**Comment by blahah** [comment]
Fixed in the search engine by adding a pre-processing step to strip XML tags 15a706d5b8a833774e050a6fddf6e3a8c8b3cd63

**Comment by pvanheus** [comment]
Seems not to fix things:

![image](https://user-images.githubusercontent.com/4154788/27672188-5a1836b4-5c99-11e7-966f-9ba7fe1d67f0.png)

is there an index that needs to be rebuilt or a cache that needs to be emptied or something?

**Comment by blahah** [comment]
ah, yes you'll need to delete the search index:

```
rm -rf ~/.sciencefair
```

will nuke the whole thing
