### ISSUE TITLE
"Linked items" in modal box do nothing (Ubuntu 16.04, v. 1.0.3)

### ISSUE THREAD

**Issue by pvanheus** [codeforscience/sciencefair#101]
Clicking "sciencefair" in the top right corner opens a model window:

![image](https://user-images.githubusercontent.com/4154788/27659862-4ba59548-5c55-11e7-8e66-30149b1c2d47.png)

There are three items - *code*, *website* and *chat* that appear to be links. Clicking on them does nothing.

**Comment by blahah** [comment]
Hmm, these are just buttons with

```js
btn.onclick = e => {
  e.preventDefault()
  opn(btnurl)
}
```

This works on OSX and Windows.

@sindresorhus any ideas why this would die without error on Ubuntu?

**Comment by sindresorhus** [comment]
Don't use `opn` with Electron. Electron has its own method for this: https://electron.atom.io/docs/api/shell/#shellopenitemfullpath

**Comment by blahah** [comment]
Ah, thanks @sindresorhus - actually you mentioned this before but I moved to `opn` rather than the electron native interface by accident. Sorry for troubling you again!
