### ISSUE TITLE
Text in the paper preview is not selectable (v. 1.0.3)

### ISSUE THREAD

**Issue by pvanheus** [codeforscience/sciencefair#102]
When clicking on a search result a paper preview (including abstract etc) is shown in the bottom part of the window. This text cannot be selected or copied. (Ubuntu 16.04, v. 1.0.3)

![image](https://user-images.githubusercontent.com/4154788/27659969-a2acc744-5c55-11e7-9505-dd9255b71b47.png)

The text in question is that which starts "More than 1500 fossils"

**Comment by pvanheus** [comment]
Thanks but the selection colour is a bit dark:

![image](https://user-images.githubusercontent.com/4154788/27686751-5fa425b2-5cd4-11e7-92f7-4da2bd787d2b.png)

Can it be a highlight rather than a darken?

**Comment by blahah** [comment]
Hmm sorry, the CSS is supposed to do this:

<img width="713" alt="screen shot 2017-06-29 at 15 53 58" src="https://user-images.githubusercontent.com/836040/27688490-64e2a364-5ce3-11e7-9e32-5005201993db.png">

for some reason it's not working. Looking into it, thanks for following up.
