### ISSUE TITLE
[v1.0.4 all platforms] Deleting is slow and still lists in 'saved'...

### ISSUE THREAD

**Issue by nickschurch** [codeforscience/sciencefair#104]
Deleting a downloading article takes a while to do with no immediate user feedback - prompted me to click it several times to see if I'd mis-clicked.

Also, downloaded paper still listed in 'saved' even after deleted.

linux deb binary install on ubuntu.

**Comment by blahah** [comment]
@nickschurch this is version `1.0.4`? I suspect there was an error if you didn't get immediate feedback/complete deletion - if you could look in the developer console that would be super helpful:

ctrl+shift+i on linux

**Comment by blahah** [comment]
I've recreated this - the cause is #107
