### ISSUE TITLE
[v1.0.4 all platforms] 'year' bar graph looks odd for missing years...

### ISSUE THREAD

**Issue by nickschurch** [codeforscience/sciencefair#105]
If I search for 'arabidopsis RNA' I get 5 results. If I select results 3, 4 and 5 (from 2 from 2016 & 1 from 2014) in the pop-up panel at the bottom of the screen I get a bar for 2014 that 1/2 the width of the 2016 bar and both the 2016 and 2014 bars have the correct numbers. There is also a 2015 bar which has '0' as a number (correctly) but appears to have some width...

Probably should either exclude it completely, or set the bar width correctly.

**Comment by blahah** [comment]
fix incoming...

### before

<img width="358" alt="screen shot 2017-06-29 at 21 57 41" src="https://user-images.githubusercontent.com/836040/27705309-2680b204-5d16-11e7-8148-9e69fa92d898.png">

### after

<img width="297" alt="screen shot 2017-06-29 at 21 57 03" src="https://user-images.githubusercontent.com/836040/27705318-2a8571a0-5d16-11e7-9cb5-32b5b0894a39.png">
