### ISSUE TITLE
stop blocking fullscreen mode for macOS & Windows users

### ISSUE THREAD

**Issue by katrinleinweber** [codeforscience/sciencefair#109]
Hello and thanks for working on this neat app :-)

Is there are specific reason why [`fullscreen:` is set to  `false`](https://github.com/codeforscience/sciencefair/blob/master/app/run.js#L35)? I haven't coded for Electron before, but from its [`BrowserWindow` docu](https://electron.atom.io/docs/api/browser-window/) I gather that `fullscreenable: true` would keep the current default behaviour, but additionally enable full-screen mode :-)

Because it was a quick change, I already PR'ed it:

**Comment by blahah** [comment]
@katrinleinweber whoa, this is awesome, thanks!

When `fullscreen` is set to true, the app opens maximised by default (or at least it did when I set that options). I didn't even realise there was an option to allow true fullscreen, and am very happy to have it. Thanks so much!

**Comment by katrinleinweber** [comment]
How it should open is very much personal preference, I guess. Me: fullscreen! Many other Mac users I saw prefer unmaximised even.

**Comment by blahah** [comment]
Agreed - I turned off that particular setting because users asked for it to be turned off, but I think your PR gives us the ideal situation when users who want it can fullscreen 👌🏾👍🏽
