### ISSUE TITLE
Syncing initial data takes a long time

### ISSUE THREAD

**Issue by j-faria** [codeforscience/sciencefair#115]
Just installed sciencefair and started it for the first time. 
It's not the best user experience to be greeted to a loading screen, which eventually takes 5+ minutes to complete. I would suggest creating a "welcome" screen which maybe introduces the app and allows the user to start "syncing initial data" when they want (warning them that it might take a few minutes).

**Comment by blahah** [comment]
Hi, thanks for reporting this. The loading screen should take a few seconds on most connections - so unless your connection is 2G or something similar this is a bug.

We will make sure this is resolved in the next couple of releases.

**Comment by blahah** [comment]
And good idea about the landing page - we will discuss design aspects of this and update here.

**Comment by dasaptaerwin** [comment]
I have downloaded ScienceFair on Windows, Mac, and Linux. The only problem occurred on my Linux machine running Ubuntu 16.04. It freezes at "Sync initial data" stage. Rebooting won't solve the problem. Thanks.

**Comment by blahah** [comment]
Thanks for your patience while we dealt with a temporary bug in Github's release API.

This issue should be solved in [`v1.0.6`](https://github.com/codeforscience/sciencefair/releases/tag/v1.0.6)
