### ISSUE TITLE
syncing stop at 25 %

### ISSUE THREAD

**Issue by samaussie** [codeforscience/sciencefair#117]
Hello, my initial syncing stop at 25 %. Tried to restart or reinstall the app or restart windows but it's still not working.

**Comment by blahah** [comment]
Hi @samaussie - sounds like there might have been an error. There will be a new release later today (~8h) to address a known bug, if you open the app then it should auto-update and recover where it left off. If not, please let me know and we can debug.

**Comment by samaussie** [comment]
Many thanks for quick response. I'll download & install new version and let you know any happen next.

**Comment by egeulgen** [comment]
Hello, the initial syncing stops at 25% for me as well. Using the latest release(v1.0.5)

**Comment by blahah** [comment]
Thanks for reporting this - and apologies the new release hasn't made it out yet. Some new issues with dependencies came to light, it will be released this evening.

**Comment by npscience** [comment]
Hi @blahah, sorry to add to the pile but a couple of us have tried the v1.0.5 for Mac today and had the same problem. I'll wait for the next release and let you know if it persists.

Good luck!

**Comment by blahah** [comment]
@npscience sorry for the delay - there's a bug in Github's release system that has been preventing me cutting this release. Every time the CI server tries to upload the macOS installer, it freezes until the server fails. Trying to upload manually does the same.

This has been going on for a month or so, and usually I can eventually upload the files if I keep retrying, but today it's not happening.

I've messaged Github support through various channels in the last hour, so I'm hoping they will provide a solution ASAP.

Thanks everyone for your patience while we figure this out.

**Comment by blahah** [comment]
Thanks all for your patience, this should be solved in [`v1.0.6`](https://github.com/codeforscience/sciencefair/releases/tag/v1.0.6)
