### ISSUE TITLE
Deleting a paper doesn't decrement 'saved' count, remove paper from view

### ISSUE THREAD

**Issue by emanuelfeld** [codeforscience/sciencefair#119]
Overview:

Select a saved paper and click delete. The paper remains visible unless the user navigates away and then revisits 'saved'. The 'saved' count at the bottom also doesn't decrement with deletion. 

Having deleted papers, saving new papers doesn't change count until the actual number of papers in the collection exceeds the previous number.

Science Fair version: 1.0.5
OS: Mac OS 10.12.5

**Comment by blahah** [comment]
Fixed in https://github.com/codeforscience/sciencefair/releases/tag/v1.0.6 :)
