### ISSUE TITLE
Add school library as a source

### ISSUE THREAD

**Issue by MrSassyBritches** [codeforscience/sciencefair#144]
Would be very beneficial to be able to add my schools Shapiro Library as a source to find papers as well as others like Google Scholar and others.

**Comment by lgro** [comment]
Thanks for you suggestion. 
In the upcoming [version 1.1](https://github.com/codeforscience/sciencefair#roadmap) users will be able to easily add datasources by themselves. This could enable your school's library to add their own datasource. Alternatively someone could add a datasource that automatically adds publications from a respective library. However, in that case one would have to be especially careful about usage/distribution rights.

How would you envision Google Scholar to be added as a datasource? To me it seems that Google Scholar and ScienceFair operate on a similar level, both a tool to search scientific repositories. So adding relevant journals as datasources might already satisfy your intentions?!

**Comment by blahah** [comment]
we are definitely interested in exploring how we might be able to support school-specific library collections. We have a separate repo for discussion datasources, so I suggest we continue over there: https://github.com/sciencefair-land/datasource-requests (existing issue https://github.com/sciencefair-land/datasource-requests/issues/19)

**Comment by blahah** [comment]
and +1 to @lgro's comment about Google Scholar - Scholar is the sort of thing we'd (very long term) seek to make obsolete with sciencefair, rather than include.
