### ISSUE TITLE
Lack of spaces in article title/description bottom details panel

### ISSUE THREAD

**Issue by todrobbins** [codeforscience/sciencefair#154]
When I click on a search result, the details panel is not rendering with spaces in either the title or description. It looks like this:

![screen shot 2017-08-03 at 9 26 33 am](https://user-images.githubusercontent.com/158590/28929881-642a8f2a-782e-11e7-85a5-82fd07c339a1.png)

I didn't find any other issues referencing this issue, so I hope this is useful.

Cheers!

**Comment by blahah** [comment]
Thanks for reporting this @todrobbins and sorry for the trouble. Can you confirm the version you're using? I have seen this in testing but thought I had resolved it.

**Comment by todrobbins** [comment]
Ah! I just realized I'm still running 1.0.0-beta10. 🙈

Just downloaded 1.0.6 and it's not an issue. Carry on!
