### ISSUE TITLE
window size should not be higher than screen size

### ISSUE THREAD

**Issue by step21** [codeforscience/sciencefair#155]
My laptop has a 1366x768 screen resolution. I am not sure atm how sciencefair sets the window size, but at least on Ubuntu 16.04 when running Unity as Desktop environment the window is drawn with such a height that the lower part is cut off. It is probably just a few pixels that are cut off, nothing important, but it is hard to actually know that for sure/find out.

**Comment by blahah** [comment]
@step21 good point! Currently the app window is created with the following settings:

```
      height: 750,
      width: 1080,
      minHeight: 750,
      minWidth: 1080,
```

The reason for having a restriction in the first place is that the interface doesn't work with a screen much small than this, but given `768` is probably quite a common screen resolution height we should lower the height default and minimum.
