### ISSUE TITLE
Science fair requires raven twice

### ISSUE THREAD

**Issue by bcomnes** [codeforscience/sciencefair#167]
https://github.com/codeforscience/sciencefair/blob/444bb75e0c73cc1e632ec833b98ba2d693668cde/app/client/lib/raven.js#L1

https://github.com/codeforscience/sciencefair/blob/444bb75e0c73cc1e632ec833b98ba2d693668cde/app/client/lib/raven.js#L41

**Comment by blahah** [comment]
well spotted! I must have been tired that day 😴

**Comment by bcomnes** [comment]
Thanks for the reference implementation! https://github.com/hypermodules/hyperamp/blob/90520f7c80d892836468f0391d795cee9e22a667/sentry.js
