### ISSUE TITLE
Install problems (SQLite bindings related)

### ISSUE THREAD

**Issue by michael** [codeforscience/sciencefair#21]
Tried to run sciencefair on my local machine on Node 5.1.1.

```js
Uncaught Error: Cannot find module '/private/tmp/sciencefair/node_modules/sqlite3/lib/binding/electron-v0.36-darwin-x64/node_sqlite3.node'
```

Anything obvious that, I'm missing?

What would be nice is if we had prerelease packages for OSX/Win just so we can demo it. Would that make sense at this stage?

**Comment by blahah** [comment]
@michael the master is not in a usable state - [this PR](https://github.com/codeforscience/sciencefair/pull/14) should work though. I agree about prerelease packages, we'll try to get something out this weel.

**Comment by michael** [comment]
Thanks! Got it running.
