### ISSUE TITLE
Global state store

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#23]
@maxogden @freeman-lab can you elaborate on what you had in mind? I'd like to get this in place before going too much further - it will get harder to do the more we build without it.

**Comment by freeman-lab** [comment]
@blahah agreed! I've been really enjoying [`choo`](https://github.com/yoshuawuyts/choo) and I sorta think we should restructure our UI/UX to use it. It basically just combines a few really light-weight modules for state management (`send-action`) and view updating (`yo-yo`) in a simple and elegant way. Also very compatible with the composable front-end work @maxogden and co have been doing over in dat land.

As I sort of created our front-end mess in the first place, I can take a stab at doing this refactoring this weekend. Agreed it'd be good to get in place before adding much more!

**Comment by blahah** [comment]
I took your initial mess and ran it through a pipeline involving a mincer, a mangle and several illegal surgical procedures. Sorry about that... If you can start converting and create some examples of best practise, I can help with the rest of the conversion.

**Comment by blahah** [comment]
We've moved to choo now 🙌, this will land in v1
