### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by npch** [codeforscience/sciencefair#24]
This is the overall ticket for installation issues.

**Comment by npch** [comment]
When installing using `npm install` the error message 
`npm ERR! Unsupported URL Type: github:blahah/yunodb`

can be resolved by upgrading npm to version >= 3.7.1

**Comment by npch** [comment]
After running `npm run dev` getting the error:

`/.../codeforscience/sciencefair/node_modules/levelup/lib/util.js:54 Uncaught LevelUPError: Failed to require LevelDOWN (Module version mismatch. Expected 47, got 14.). Try ``npm install leveldown`` if it's missing`

**Comment by blahah** [comment]
@npch this is because the leveldown installed is compiled against the wrong version of node. If you `rm -r node_modules` then `npm install` again does it work?

**Comment by blahah** [comment]
@npch also, I think you must be using a very old node - 0.10 or something like that? The current latest version is 6.0! I think we probably can only support 4.0 and above.

**Comment by npch** [comment]
I've upgraded to node 4.4.5 but still getting similar issues - will remove
modules and retry

**Comment by mafintosh** [comment]
This is because electron is using a different version of node that the one npm is using. Makes installing native modules more difficult than it should be. I think @juliangruber has a one-liner though that fixes this

**Comment by blahah** [comment]
awesome that there's a fix! @juliangruber is it something we can put in the npm postinstall script?

**Comment by blahah** [comment]
looks like this is the command, from https://github.com/mafintosh/prebuild/pull/125 :

```
npm rebuild --target=1.1.3 --abi=48
```

and it requires prebuild `4.2.2`

**Comment by mafintosh** [comment]
prebuild 4.2.2 ships with latest leveldown

**Comment by blahah** [comment]
@mafintosh looks like leveldown 1.4.6 has prebuild 4.1.1 https://github.com/Level/leveldown/blob/master/package.json#L35 ?

**Comment by mafintosh** [comment]
@blahah the "hat" makes it download 4.2.2 (latest)

**Comment by blahah** [comment]
:blush: d'oh

**Comment by Adrianzo** [comment]
```
$ nodejs -v
v6.3.0
$ npm -v
3.10.3
$ uname -a
Linux 7548 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I'm unable to install this software. The reason is that my distro isn't recognized...

Full output of running `npm install` after clonning the repository:
```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /media/xvzf/windata/LAB/sciencefair/npm-debug.log
```

**Comment by chartgerink** [comment]
Really excited about what I am seeing of ScienceFair and hope to be able to install :-) However, just like above, arch distro not supported? More than happy to try out stuff and contribute fix with some help.

```
[chjh@ww110039 sciencefair]$ node -v
v6.9.4
[chjh@ww110039 sciencefair]$ npm -v
3.10.10
[chjh@ww110039 sciencefair]$ uname -a
Linux ww110039.uvt.nl 4.9.6-200.fc25.x86_64 #1 SMP Thu Jan 26 10:17:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

npm ERR! Linux 4.9.6-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chjh/sciencefair/npm-debug.log
```

**Comment by joehand** [comment]
The `appdmg` dependency should only be needed if you want to build the app. You should be able to run it without that.

Does the install fail totally? If so, maybe remove that dependency from package.json.

**Comment by chartgerink** [comment]
Ah cheers! Now on to the next bug not related to install issues ;-) (white screen + crash after search starts; will post to other issue if I can't debug)

**Comment by joehand** [comment]
Nice! Haven't completely followed development here, but the `v1_dev` branch is more likely to work at this point. I'd recommend using that one if you aren't already =).

**Comment by blahah** [comment]
Indeed, all development is currently in the `v1_dev` branch - that's the only branch expected to work right now.

To start the app:

1. clone the repo
2. `npm install`
3. `npm run dev` (gives you devtools like the element inspector) or `npm run start`

**Comment by blahah** [comment]
`v1_dev` work has now been merged into master as we approach v1 beta release. The app *should* run `npm run dev` or `npm run start` on OSX, windows and linux.
