### ISSUE TITLE
Approaching browse/download problem

### ISSUE THREAD

**Issue by MMMalik** [codeforscience/sciencefair#3]
Hi, 
for starters, I would like to say, that I really like the idea behind this app. 
I was wondering, however, how do you plan to approach the problem of browsing a journal's archive and downloading papers of interest?

For example, two acknowledged open-acces journals in chemistry, [Molecules](http://www.mdpi.com/journal/molecules) ans [BeilsteinJOC](https://www.beilstein-journals.org/bjoc/home/home.htm), do not offer a public API (as far as I know). There is a possibility of concluding the URLs and thus making the requests, but it does not seem to be a "clean" approach.
There is another option (in my opinion a better one), where you use [PubMed](http://www.ncbi.nlm.nih.gov/pubmed) API to do the job. As far as I know, there is no JavaScript wrapper for that, so it has to be written. 

Either way, I would like to participate somehow in the project by, for example, writing a JS module for PubMed API (I've already created a [PubChem API wrapper](https://github.com/MMMalik/pubchem-access)). I see myself rather as a hobbyist JS programmer, since I'm still a PhD student (Chemistry), but I'll be glad to help.

**Comment by Blahah** [comment]
Hey, thanks for your interest! We actually just hammered out some details of this last night.

We're pre-generating a full index of open-access papers, starting with EuropePMC (should be done by tomorrow). This will be distributed with the app using [dat](dat-data.com).

The initial indexes will be generated by parsing full data dumps. For example, EuropePMC data is here: europepmc.org/FtpSite, and PubMed data is here: http://www.ncbi.nlm.nih.gov/pmc/tools/ftp/.

Later we will merge in other data sources (e.g. CrossRef, DOAJ, Academic Graph, etc.) and allow users to add their own.

More generally we've tackled these issues on the [ContentMine](https://github.com/ContentMine/) project by using a combination of API access tools (see [getpapers](https://github.com/ContentMine/getpapers)) and collections of declarative scrapers for providers that don't deposit their data anywhere useful (see [quickscrape](https://github.com/ContentMine/quickscrape), [scraperjson](https://github.com/ContentMine/scraperjson) and [journal-scrapers](https://github.com/ContentMine/journal-scrapers)).

Ways to help right now include:
- watch the repo so you'll get notified when new issues are added
- take a look at the linked projects above which are more ready for contributors right now

And here's a small :cactus: as a prize for creating the first issue.

**Comment by maxogden** [comment]
@mmmalik also we were thinking of other data preprocessing we could to to make the paper metadata browsing/search more fun/valuable. One idea was to try to extract figures from the papers (using some pdf to png pipeline that was could intelligently create screenshots of the figures in the pdf, etc). If you have any ideas like that it could be a good way to start experimenting.
