### ISSUE TITLE
Decentralised Web Summit demo

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#31]
Science Fair will be demoed at the [Decentralised Web Summit](http://www.decentralizedweb.net/) by @karissa 

This is the stuff we need to do to prep:

- [x] sync the eLife corpus (@blahah) --> https://github.com/codeforscience/sciencefair-elife
- [x] generate eLife bibJSON metadata collection by parsing the XML (@blahah)
- [x] code for linked metadata and files hyperdrive live feeds (@mafintosh)
- [x] strip back Science Fair to the core features (@blahah)
- [x] electron OSX app packaging script (@freeman-lab)
- [x] publish the eLife metadata and files as a linked feed (@blahah + @mafintosh)
- [x] seed the feed from a bunch of places so it's fast (@mekarpeles ?)
- [x] incorporate the feed as the default data source (@blahah)
- [x] run through the planned demo and iron out bugs (@karissa)
- [ ] BONUS: add this paper + PDF viewing [[landing](http://science.sciencemag.org/content/341/6146/616.summary), [DOI record](http://api.crossref.org/works/10.1126/science.1241625), [PDF](http://sites.nationalacademies.org/cs/groups/pgasite/documents/webpage/pga_084791.pdf)]

Working in the `dat` branch...

**Comment by blahah** [comment]
toy feed for eLife papers is seeding, people welcome to join the swarm:

```
dat b7266cf1be1d61ccf422ec854fca814b87cf7bdce960fc2c5e9a138b7bc98021
```

**Comment by blahah** [comment]
OK, the toy feed is now retired and we have a real feed:

```
dat c0b6950cde25661786cc75b8951e0bf4a6a20e10dc8f3025ab8b60ba16682dbb
```

**Comment by blahah** [comment]
@karissa here's a workflow that should work:

- fresh clone, make sure you're on node `v6`
- `git checkout dat`
- `npm install && npm run rebuild`
- `npm run dev`

Now you'll see the message 'Loading data sources...' while it connects to the hyperdrive for the first time and syncs the metadata. When that's done, you should see something like...

<img width="2032" alt="screenshot 2016-06-08 11 47 05" src="https://cloud.githubusercontent.com/assets/836040/15891902/bd6261d2-2d6e-11e6-8080-fbea02dc3dcc.png">

If you search for `cancer` you'll see...

<img width="2032" alt="screenshot 2016-06-08 11 48 39" src="https://cloud.githubusercontent.com/assets/836040/15892048/870c0740-2d6f-11e6-94c6-32518c896c2f.png">

Pick a paper and hover over it, you'll see the downward arrow indicating that the paper needs to be downloaded.

<img width="2032" alt="screenshot 2016-06-08 11 48 50" src="https://cloud.githubusercontent.com/assets/836040/15892068/aaf1607e-2d6f-11e6-868e-718ba9870cd7.png">

Click it and the paper files (XML + figures) will download from hyperdrive, and then the icon will change to a lens.

<img width="2032" alt="screenshot 2016-06-08 11 48 57" src="https://cloud.githubusercontent.com/assets/836040/15892070/b10176f2-2d6f-11e6-99ed-b26b0150c193.png">

Click the lens and you'll open the paper in the reader. You can show the figures panel on the right - all the figures are served off hyperdrive.

<img width="2032" alt="screenshot 2016-06-08 11 49 18" src="https://cloud.githubusercontent.com/assets/836040/15892077/b8b0d0b4-2d6f-11e6-8dd4-d966008e3343.png">

In the reader view you can see the `doi` on the left just above the word **Abstract**, e.g. `10.7554/eLife.02242`. All the files for the this paper are stored in this dat:

```
c0b6950cde25661786cc75b8951e0bf4a6a20e10dc8f3025ab8b60ba16682dbb
```

under the subdirectory

```
02242
```

@karissa @mafintosh @maxogden hopefully you can then demonstrate that you can pull those same files from the dat somehow in another place, like the browser?

Do we need anything else for this? I need to prep for a 3 month trip, so can only do little bits after this - hopefully someone else can hack it together if more is needed?

Here's the place where I butchered hyperdrive into the app https://github.com/codeforscience/sciencefair/blob/dat/app/lib/hyperdrive.js.

**Comment by mafintosh** [comment]
@blahah your code looks great. thanks for your hard work the last few days. i'll try to get science fair working as a hybrid client today so it can seed to the browser

**Comment by blahah** [comment]
@mafintosh sweet :)

@karissa I forgot to point out explicitly, but the subdirectory that the files are found in is the last part of the DOI, so `10.7554/eLife.02242` -> `02242`. You probably already noticed but I realised I wasn't clear.

**Comment by blahah** [comment]
@karissa just noticed that when I created the feed I messed up the metadata for some of the articles - some have authors missing and don't seem to sync properly. When demoing choose a paper that's displaying the author :D

**Comment by blahah** [comment]
I guess I should be able to update the original feed with fixed info... @mafintosh what do I edit here to make it so that I'm appending to the feed I served up earlier?

```
var hyperdrive = require('hyperdrive')
var level = require('level')
var raf = require('random-access-file')
var walker = require('folder-walker')
var through = require('through2')

var drive = hyperdrive(level('./elife_webdemo.db'))
var archive = drive.createArchive({
  file: function (name) {
    return raf('./elife/' + name)
  },
  live: true
})

walker('./elife').pipe(through.obj(visit))
.on('finish', function () {
  var link = archive.key.toString('hex')
  console.log(link, '<-- this is your hyperdrive link')
})
.on('error', console.trace)

function visit (data, enc, cb) {
  archive.append({ type: data.type, name: data.relname }, cb)
}

var discovery = require('discovery-swarm')
var defaults = require('datland-swarm-defaults')

var swarm = discovery(defaults({
  hash: false,
  stream: function () {
    return archive.replicate()
  }
}))

swarm.join(archive.discoveryKey)
```

**Comment by mafintosh** [comment]
@blahah pass the archive key in the createArchive constructor (this needs to be on the same computer where you originally created the feed - that one has the private key)

``` js
var archive = drive.createArchive(<insert-key-here>, {
  file: function (name) {
    return raf('./elife/' + name)
  },
  live: true
})
```

then just filter the files you don't want to update here,

``` js
function visit (data, enc, cb) {
  if (data.relname !== 'the-files-you-are-looking-for') return cb()
  archive.append({ type: data.type, name: data.relname }, cb)
}
```

**Comment by mafintosh** [comment]
alternatively you can just create new feed with the updated data if thats easier right now

**Comment by blahah** [comment]
It took ages to build to feed originally - it's 12GB, so I think I'll fix the metadata and just append it. Thanks for the help :D

**Comment by mafintosh** [comment]
cool! i'll do a module soon that'll just re-index new files so o/ becomes a lot easier

**Comment by blahah** [comment]
nice :) I've got most of a cli made for creating science fair data feeds - if you make that module I'll swap it in

**Comment by mafintosh** [comment]
perfect!

**Comment by mafintosh** [comment]
this reminded me that we really need an undo function hehe, https://github.com/mafintosh/hypercore/issues/27

**Comment by blahah** [comment]
Attempt at a 'fresh start' script:

```
nvm use 6 # or whatever your favourite way to make sure you use node 6
rm -rf ~/.sciencefair/data/elife.*
git clone git@github.com:codeforscience/sciencefair.git
cd sciencefair
git checkout dat
npm install
npm run rebuild
npm run dev
```

cc @karissa @mafintosh

**Comment by blahah** [comment]
Culminated in @karissa's demo:

https://youtu.be/Yth7O6yeZRE?t=8h16m
