### ISSUE TITLE
UX for 'Collections'

### ISSUE THREAD

**Issue by karissa** [codeforscience/sciencefair#32]
It's confusing to me to have 'collections' be so prominent - it'd be nice if it was a drawer and not open by default

**Comment by karissa** [comment]
somehow i had an older version

**Comment by blahah** [comment]
@karissa yeah that was a demo where I made some bad choices 😊 

It's a relevant thing to keep open though - me and @freeman-lab came up with some ideas the other day, and it would be great to get your feedback. We're thinking a collection should just be a tag - you can tag any paper and you can view all papers with a specific tag.

@freeman-lab wanna put your nice mocks in here?

**Comment by blahah** [comment]
here's one:

![](https://files.gitter.im/codeforscience/community/GQ3y/Screen-Shot-2016-06-07-at-11.55.51-AM.png)

**Comment by blahah** [comment]
@freeman-lab it would be cool to also mock up the interface for viewing one or more tags.

We previously discussed that when you click on a tag, it would add the tag to the search bar as a filter. We also want a user to be able to do a search for one or more tags and have them be recognised as tags and turned into an `AND` filter.

I'm thinking that is a user starts typing we could autosuggest any tags that fuzzy match what they've typed so far. If they click on one of the suggestions it adds the filter, with the tag badge appearing to the right of the search bar (inside the bar).

**Comment by blahah** [comment]
Now implemented in [v1_dev branch](https://github.com/codeforscience/sciencefair/tree/v1_dev).

To see how the collections interface works, search for `cat` and click on any paper. You'll see the detail view with tags displayed:

- Clicking on a tag adds it as a filter to the search.
- Hovering over a tag in the detail view shows an `x` button which deletes the tag from this paper. 
- Hovering over a tag in the search shows an `x` which removes it from the search filter.
- There's a `+` button in the detail view that opens a field for adding a tag.
- Typing a `#` followed by any other characters in the search bar will display an autocomplete for tags matching the characters following the `#`. The number of papers with each tag is displayed alongside the tag, and characters that match the search are highlighted yellow. Selecting a tag from the autocomplete dropdown adds it as a filter to the search.

**Comment by blahah** [comment]
Closing - interface will land in v1
