### ISSUE TITLE
Where are the contributing guidelines?

### ISSUE THREAD

**Issue by acabunoc** [codeforscience/sciencefair#34]

**Comment by joehand** [comment]
@acabunoc it looks like some discussion on the contributing guidelines and a code of conduct was started in this [PR](https://github.com/codeforscience/sciencefair/pull/30) but hasn't been merged yet. The [draft contributing guide is here](https://github.com/codeforscience/sciencefair/blob/documentation/CONTRIBUTING.md).

**Comment by acabunoc** [comment]
Thanks for the pointer @joehand! Anything blocking this from being merged in?

**Comment by blahah** [comment]
Really just that I am currently refactoring the entire codebase, and don't want contributions until I push something not completely broken. But we perhaps should have an interim CONTRIBUTING.md that explains this...

**Comment by acabunoc** [comment]
> But we perhaps should have an interim CONTRIBUTING.md that explains this...

Yes please!

**Comment by stephwright** [comment]
Just me nudging on this a little bit... 👈

**Comment by blahah** [comment]
At long last, PR has been merged :)
