### ISSUE TITLE
Show a thumbnail for each paper

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#5]
@freeman-lab's [pdf-to-png](https://github.com/freeman-lab/pdf-to-png) allows creating a thumbnail from a PDF.

It will be slow to generate these on the fly for each client - it requires downloading a full PDF to create the thumbnail. So a nice setup task is to generate a dataset of thumbnail images from all the papers in our set.

We can start with EuropePMC - download all the PDFs and use `pdf-to-png` to generate thumbnails with DOIs as filenames. But it should be equally doable for all the open access sources, and even for non-OA papers a thumbnail should be legitimate.

It would be cool to put the images somewhere reusable and behind a nice API.

**Comment by onbjerg** [comment]
@blahah Maybe S3?

**Comment by blahah** [comment]
@onbjerg that's definitely an option - somewhere free would be even better :)

**Comment by onbjerg** [comment]
@blahah GitHub? 😁

**Comment by blahah** [comment]
@onbjerg yeah that's what I'm thinking! Could also do zenodo and use some sort of comtent addressable format to store a collection of images.

**Comment by blahah** [comment]
This is really related to PDFs, which aren't planned to be included in v1. Closing this but we can revisit later if we decide to add PDFs.
