### ISSUE TITLE
Italics text in article titles not rendered in search results

### ISSUE THREAD

**Issue by gmaciocci** [codeforscience/sciencefair#52]
Italics text in article titles not rendered in search results.

Example: "Homo Naledi" in http://doi.org/10.7554/eLife.10627

**Comment by blahah** [comment]
This is specific to the eLife datasource. I have tested that italic text in general is displayed, but it isn't being published in the datasource. A new live source will be launched before beta.

**Comment by blahah** [comment]
All entries with italics now display, but the italic text is actually not italic - I think this is because the font doesn't have an italic. I'll look deeper.

**Comment by greggraf** [comment]
It looks like the font supports italics, but the tag wrapping "Homo naledi" is `<italics>` which is not an html element. If the element is changed to `<i>` the text is rendered as italicized.

**Comment by blahah** [comment]
@greggraf well spotted, thank you!

The problem is that the metadata (title, abstract, etc.) is extracted from the JATS XML, where apparently `<italics>` is used. So we need to convert tags in the metadata to their HTML equivalents, if any.
