### ISSUE TITLE
Would be good to know what the software actually aims to do

### ISSUE THREAD

**Issue by weaverbel** [codeforscience/sciencefair#57]
Hi I came and checked it out but have no idea what Science Fair is meant to do, or who it's for. Maybe add a sentence or two about the project and what it is trying to achieve, so people can then evaluate and comment on the basis of the project's goals?

I am sure that would help others who come visit too. And congrats on finally getting a big project out the door.

**Comment by blahah** [comment]
@weaverbel thanks, I wasn't expecting this much attention today, but I've now [updated the README](https://github.com/codeforscience/sciencefair/blob/master/README.md) to give a bit more information. Website will be landing tomorrow.

Does this clarify the purpose of the project enough?

**Comment by rmflight** [comment]
That really clarifies what it is about to me @blahah . I knew some about it based on your tweets and other sources, but this definitely helps me. Now I'm really excited to try it out. Now if only I could get a version of Lens reader for local files on my tablet / phone ....

**Comment by weaverbel** [comment]
Thanks @blahah - all good now and I might even talk it up tomorrow to a room full of captive librarians. Never underestimate the power of Twitter - once you tweet, you can be swarmed in a heartbeat. Good luck with everything!

**Comment by blahah** [comment]
thanks both!
