### ISSUE TITLE
Library not loaded libsodium

### ISSUE THREAD

**Issue by maxogden** [codeforscience/sciencefair#62]
using sciencefair-1.0.0-beta8.dmg on mac os 10.10.5. update: same on sciencefair-1.0.0-beta7.dmg

<img width="1192" alt="screen shot 2017-05-06 at 10 03 48 am" src="https://cloud.githubusercontent.com/assets/39759/25774436/686744ba-3243-11e7-95f1-f15505556cf4.png">

**Comment by blahah** [comment]
hmm, not sure why this is happening

tagging @mafintosh @juliangruber

we are specifying the same version of electron in the dependencies as in the the rebuild scripts

**Comment by blahah** [comment]
Note that I haven't release beta7 or beta8 as official releases yet because the windows builds are failing on appveyor. I don't think the failure is related to this though.

@maxogden please could you see if this happens with beta6 (and if so, if you have the time, step back through the releases until it doesn't give this error?)

**Comment by juliangruber** [comment]
looks like your libsodium version isn't compatible with sodium-native, but unsure what could case that. It doesn't seem to be related to rebuilding for a specific abi though.

**Comment by mafintosh** [comment]
@maxogden if you npm install sodium-native manually, can you require it without errors in a simple node script?

**Comment by pfrazee** [comment]
> I got the same error and brew update libsodium did the trick for me. Also on 10.10.5.

^ Suggestion on our thread

**Comment by mafintosh** [comment]
Wait, that makes no sense at all to me. We vendor libsodium and do not link against the globally installed one.

**Comment by pfrazee** [comment]
Hmm. Well lets try it and find out.

**Comment by amorrissette** [comment]
brew install libsodium worked for me. running beta10 on 10.10.5

**Comment by blahah** [comment]
@mafintosh any clue why this is happening?

**Comment by mafintosh** [comment]
@blahah no, but the wasm version is coming out very soon which will always work

**Comment by mafintosh** [comment]
@blahah would still be useful if i could get someone on old macos to require("sodium-native") from inside the electron build directory (using node). That will help me find the root cause

**Comment by blahah** [comment]
@mafintosh let me see what my oldest running macOS is

**Comment by blahah** [comment]
@mafintosh OK, I found an MBP on 10.10.1 and was able to replicate this issue.

Whether I require from `electron` or `node`, I get this error:

```
Error: dlopen(/Applications/ScienceFair.app/Contents/Resources/app/node_modules/sodium-native/prebuilds/darwin-x64/node-51.node, 1): Library not loaded: @loader_path/libsodium.dylib
  Referenced from: /Applications/ScienceFair.app/Contents/Resources/app/node_modules/sodium-native/prebuilds/darwin-x64/node-51.node
  Reason: no suitable image found.  Did find:
	/Applications/ScienceFair.app/Contents/Resources/app/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib: code signature invalid for '/Applications/ScienceFair.app/Contents/Resources/app/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib'

	/Applications/ScienceFair.app/Contents/Resources/app/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib: code signature invalid for '/Applications/ScienceFair.app/Contents/Resources/app/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib'

    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at load (/Applications/ScienceFair.app/Contents/Resources/app/node_modules/node-gyp-build/index.js:13:10)
    at Object.<anonymous> (/Applications/ScienceFair.app/Contents/Resources/app/node_modules/sodium-native/index.js:1:101)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

The prebuild files are present, but can't be loaded.

However, on the same machine if I install `sodium-native` in a clean dir, I can require that fine from `electron` and `node`.

One difference is that the dylibs distributed with my app are codesigned whereas the fresh install wasn't. I am guessing that the beaker app is also signed (@pfrazee ?). Possibly the issue is that on older macOS the algorithm for choosing the codesign checksum was different: https://stackoverflow.com/a/41868747/835428

Perhaps if prebuilds were run with these flags set:

```
export  LDFLAGS="-mmacosx-version-min=10.9"   
export   CFLAGS="-mmacosx-version-min=10.9"   
export CXXFLAGS="-mmacosx-version-min=10.9"
```

It might work?

**Comment by blahah** [comment]
I've confirmed this solved the bug for sciencefair. We rebuild the prebuild for sodium-native when packaging releases with electron-builder: https://github.com/codeforscience/sciencefair/blob/master/.travis.yml#L43-L47.

@mafintosh has promised to have the sodium-native builds use the same flags when they are being prebuilt, so think this is now solved. Fix will be out in the v1 release by Monday.

Thanks everyone for your help with this!

**Comment by mafintosh** [comment]
@blahah heads up that i'm seeing some pretty serious performance regressions on some on the benchmarks by applying those flags. could be a fluke, so i'll do some more scientific testing but this are the results:

#### no-special-flags

```
> hypercore@6.6.3 bench /Users/maf/dev/node_modules/hypercore
> cd bench && ./all.sh

> git checkout 2d9a7a3

# clearing cache

> rm -rf cores

# running all benchmarks

> node write-16kb-blocks.js
81221015 bytes/s
4954 blocks/s

> node write-512b-blocks.js
3106155 bytes/s
6066 blocks/s

> node write-64kb-blocks-static.js
378344546 bytes/s
5769 blocks/s

> node write-64kb-blocks.js
209592391 bytes/s
3196 blocks/s

> node copy-64kb-blocks.js
194906847 bytes/s
2972 blocks/s

> node read-16kb-blocks-proof.js
178837745 bytes/s
10908 blocks/s

> node read-16kb-blocks.js
340654131 bytes/s
20660 blocks/s

> node read-512b-blocks.js
9783317 bytes/s
19090 blocks/s

> node read-64kb-blocks-linear.js
732429620 bytes/s
11160 blocks/s

> node read-64kb-blocks-proof.js
745136588 bytes/s
11354 blocks/s

> node read-64kb-blocks.js
1169653403 bytes/s
17789 blocks/s

> node replicate-16kb-blocks.js
67615983 bytes/s
4125 blocks/s

> node replicate-64kb-blocks.js
138475860 bytes/s
2112 blocks/s

# re-running all benchmarks

> node write-16kb-blocks.js
102417190 bytes/s
6246 blocks/s

> node write-512b-blocks.js
3294300 bytes/s
6433 blocks/s

> node write-64kb-blocks-static.js
304953656 bytes/s
4650 blocks/s

> node write-64kb-blocks.js
265646171 bytes/s
4051 blocks/s

> node copy-64kb-blocks.js
203862127 bytes/s
3109 blocks/s

> node read-16kb-blocks-proof.js
193816213 bytes/s
11812 blocks/s

> node read-16kb-blocks.js
344589802 bytes/s
20978 blocks/s

> node read-512b-blocks.js
9924058 bytes/s
19371 blocks/s

> node read-64kb-blocks-linear.js
766411009 bytes/s
11677 blocks/s

> node read-64kb-blocks-proof.js
692736660 bytes/s
10556 blocks/s

> node read-64kb-blocks.js
1187767504 bytes/s
18083 blocks/s

> node replicate-16kb-blocks.js
68182742 bytes/s
4160 blocks/s

> node replicate-64kb-blocks.js
150700606 bytes/s
2299 blocks/s
```

#### with-the-min-flag

```
> hypercore@6.6.3 bench /Users/maf/dev/node_modules/hypercore
> cd bench && ./all.sh

> git checkout 2d9a7a3

# clearing cache

> rm -rf cores

# running all benchmarks

> node write-16kb-blocks.js
24726921 bytes/s
1508 blocks/s

> node write-512b-blocks.js
1644051 bytes/s
3210 blocks/s

> node write-64kb-blocks-static.js
37389157 bytes/s
570 blocks/s

> node write-64kb-blocks.js
37398273 bytes/s
570 blocks/s

> node copy-64kb-blocks.js
35789008 bytes/s
546 blocks/s

> node read-16kb-blocks-proof.js
190244830 bytes/s
11595 blocks/s

> node read-16kb-blocks.js
385129779 bytes/s
23405 blocks/s

> node read-512b-blocks.js
10264056 bytes/s
20035 blocks/s

> node read-64kb-blocks-linear.js
653923157 bytes/s
9947 blocks/s

> node read-64kb-blocks-proof.js
446276734 bytes/s
6803 blocks/s

> node read-64kb-blocks.js
841490457 bytes/s
12810 blocks/s

> node replicate-16kb-blocks.js
16847766 bytes/s
1028 blocks/s

> node replicate-64kb-blocks.js
23358462 bytes/s
356 blocks/s

# re-running all benchmarks

> node write-16kb-blocks.js
24530335 bytes/s
1496 blocks/s

> node write-512b-blocks.js
1641272 bytes/s
3205 blocks/s

> node write-64kb-blocks-static.js
37810473 bytes/s
576 blocks/s

> node write-64kb-blocks.js
36671510 bytes/s
559 blocks/s

> node copy-64kb-blocks.js
36954220 bytes/s
563 blocks/s

> node read-16kb-blocks-proof.js
186932768 bytes/s
11401 blocks/s

> node read-16kb-blocks.js
348617475 bytes/s
21222 blocks/s

> node read-512b-blocks.js
9975038 bytes/s
19475 blocks/s

> node read-64kb-blocks-linear.js
674037554 bytes/s
10272 blocks/s

> node read-64kb-blocks-proof.js
686974935 bytes/s
10469 blocks/s

> node read-64kb-blocks.js
1168380657 bytes/s
17789 blocks/s

> node replicate-16kb-blocks.js
18190381 bytes/s
1110 blocks/s

> node replicate-64kb-blocks.js
23221562 bytes/s
354 blocks/s
```

The write/replicate results are the ones that use sodium-native. Again, could just be a fluke and will report back once I've done some more testing

**Comment by mafintosh** [comment]
Note to self: this could be because sodium relies heavily on SSE instructions which might only be available in new versions of macOS.

**Comment by mafintosh** [comment]
If this turns out to be non fixable, we could ship two prebuilds for macOS, a compat version and a latest one.

**Comment by blahah** [comment]
Hmm, that is pretty huge. Is it possible to make prebuilds for different OSX versions? Alternatively I can just do a separate build of sciencefair for older OSX models.

**Comment by blahah** [comment]
update: @mafintosh did some testing and found that the flags shared above always cause a signficant performance decrease. So, rather than build with them, he has made the `sodium-universal` module [fall back to a js & webassembly version](https://github.com/sodium-friends/sodium-universal/commit/d635fde662a3f343d0bbfa20fb25c4ea49b33f85) if the native one can't be loaded. This will give high performance if the environment supports webassembly (as the electron we use does).

So, people encountering this issue in other projects have two options:

- rebuild `sodium-native` with the flags above when packaging for osx 10.9-10.10
- use `sodium-universal`

**Comment by pfrazee** [comment]
Ok we'll look into that option. Thanks for the help @blahah
