### ISSUE TITLE
Ubuntu dev from command line works, Deb installer hangs during sync

### ISSUE THREAD

**Issue by rmflight** [codeforscience/sciencefair#63]
If I install using npm and everything from command line, everything works, but installing from release .deb gets to 99% sync, and then subsequent restart just has the tiles flickering.

**Comment by blahah** [comment]
@rmflight thanks for reporting this. Which beta are you using?

could you try beta6: https://github.com/codeforscience/sciencefair/releases/tag/v1.0.0-beta6

and then if you experience the same bug, could you please try  <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>I</kbd> or <kbd>F12</kbd> to open the devtools, and report any errors from the terminal back here?

**Comment by blahah** [comment]
note that if we still have an issue with the deb vs the git clone route, that suggests a problem with the distribution packaging setup

**Comment by rmflight** [comment]
I was using beta 5, I'll try tomorrow w/ beta 6 and get back to you.

**Comment by blahah** [comment]
thanks @rmflight  - it's probably best to `rm -rf ~/.sciencefair` before retrying, in case there's any file corruption or bugs from the previous version lurking in the data.

**Comment by rmflight** [comment]
Tried beta-6 from .deb on a "relatively" fresh Ubuntu VM I keep around for testing, and it worked. Synce'd and able to search and download and read no problem.

**Comment by blahah** [comment]
Brilliant, thanks for investigating @rmflight :)
