### ISSUE TITLE
Lens view not loading, locking up app

### ISSUE THREAD

**Issue by gmaciocci** [codeforscience/sciencefair#64]
[Beta6] After successfully downloading papers, double clocking them from Saved does not load Lens. Furthermore, while hover highlighting is still present, all UI elements lose click interaction - the app's UI is essentially locked up after attempting to read a paper.

**Comment by blahah** [comment]
@gmaciocci which OS is this?

Could you please try opening the devtools,:

- macOS: <kbd>Cmd</kbd> <kbd>Alt</kbd> <kbd>I</kbd> or <kbd>F12</kbd>
- Windows: <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>I</kbd> or <kbd>F12</kbd>

Under the `console` tab there should be one or more errors - if you could copy them here that would be awesome.

For the next release I hope to have these errors reporting directly to a server.

**Comment by gmaciocci** [comment]
@blahah  MacOS.

http://doi.org/10.7554/eLife.10627

`/Applications/ScienceFair.app/Contents/Resources/app/client/views/reader.js:45 Uncaught TypeError: Cannot read property 'source' of undefined
    at reader (/Applications/ScienceFair.app/Contents/Resources/app/client/views/reader.js:45)
    at /Applications/ScienceFair.app/Contents/Resources/app/node_modules/choo/index.js:43
    at emit (/Applications/ScienceFair.app/Contents/Resources/app/node_modules/nanorouter/index.js:47)
    at Function.<anonymous> (/Applications/ScienceFair.app/Contents/Resources/app/node_modules/choo/index.js:58)
    at redraw (/Applications/ScienceFair.app/Contents/Resources/app/node_modules/nanoraf/index.js:28)
reader @ /Applications/ScienceFair.app/Contents/Resources/app/client/views/reader.js:45
(anonymous) @ /Applications/ScienceFair.app/Contents/Resources/app/node_modules/choo/index.js:43
emit @ /Applications/ScienceFair.app/Contents/Resources/app/node_modules/nanorouter/index.js:47
(anonymous) @ /Applications/ScienceFair.app/Contents/Resources/app/node_modules/choo/index.js:58
redraw @ /Applications/ScienceFair.app/Contents/Resources/app/node_modules/nanoraf/index.js:28
/Applications/ScienceFair.app/Contents/Resources/app/node_modules/nanologger/index.js:81 `

**Comment by blahah** [comment]
@gmaciocci perfect thanks, that should be enough to debug it this evening

**Comment by blahah** [comment]
I can't recreate this issue in the latest betas, so I'm closing for now. Please reopen if you experience it again.

**Comment by blahah** [comment]
I actually *did* manage to recreate this eventually, by accident. The problem was a race condition between single and double-click handlers. Fix incoming.
