### ISSUE TITLE
cmd+a doesn't work in search bar

### ISSUE THREAD

**Issue by yoshuawuyts** [codeforscience/sciencefair#67]
I wanted to select all text to clear it but it wouldn't work. Perhaps b/c preventDefault is called? Idk haha. Anyway: figured feedback might be useful (:

**Comment by blahah** [comment]
thanks, yup need to fix this

the search bar is quite hacky with caching and state etc - ultimately I'd like to get it cleaned up to something less complex

**Comment by blahah** [comment]
should be fixed in `v1.0.6` https://github.com/codeforscience/sciencefair/releases/tag/v1.0.6
