### ISSUE TITLE
modal can't be dismissed using escape key

### ISSUE THREAD

**Issue by yoshuawuyts** [codeforscience/sciencefair#68]
I'm big on keybindings I guess haha; seemed like unexpected behavior to me.

I should probs update https://github.com/shama/modal-element at some point, but ref code for this can be found here: https://github.com/yoshuawuyts/base-elements/blob/master/modal.js

**Comment by blahah** [comment]
@yoshuawuyts yeah there's def a load more keybindings needed. O pretty much only made them work for manipulating selections of results (except ctrl-a)

issues for any you notice missing are greatly appreciated :)

**Comment by blahah** [comment]
(issues or PRs!)
