### ISSUE TITLE
cmd-v paste 

### ISSUE THREAD

**Issue by jacobrosenthal** [codeforscience/sciencefair#70]
Paste (cmd-v on mac) doesn't paste in the search bar or datasources modal

I know from other issues you're generally aware of these, but you asked for more documentation tracking them, so here goes.

Excited to see your progress. Youve got my star and watch..

**Comment by blahah** [comment]
thanks for the report, it's on the list :)

**Comment by blahah** [comment]
should be fixed in `v1.0.6` https://github.com/codeforscience/sciencefair/releases/tag/v1.0.6
