### ISSUE TITLE
Windows leveldb LOCK issues

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#71]
On Linux and OSX, [beta9](https://github.com/codeforscience/sciencefair/releases/tag/v1.0.0-beta9) seems to work pretty well. On my rather paltry windows testing machine however, the app appears to complete the initial loading and presents a search screen, but never returns any results.

When I open the devtools console (<kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>I</kbd> or <kbd>F12</kbd>), I get an error from leveldb, that the process cannot get a handle on the LOCK file.

I initially thought that this was a problem with the way [leveldb](https://github.com/google/leveldb/blob/3080a45b626f8ddb474bc5e860796a48b51b3cf0/db/filename.cc#L55) constructs the LOCK file path (i.e. with a `/` as opposed to an OS-specific path separator, but after trying to manipulate the path inside a running electron instance I don't think that's true.

I'm looking for anyone with a Windows machine (preferably better than my netbook) and some knowledge of levelDB to help debug. If any interested parties could download [beta9](https://github.com/codeforscience/sciencefair/releases/tag/v1.0.0-beta9), run it, and if anything seems off open the console and paste the error here I'd appreciate it.

If anyone can offer any insight into the issue (assuming it is reproducible), that would be even better.

**Comment by cboursnell** [comment]
Windows10 Surface Pro 4 the first error in the console is:
```
events.js:160
err
cause: Error: IO error: LockFile C:\Users\cbour\.sciencefair\collection\docstore/LOCK: The process cannot access the file because it is being used by another process.
message:"IO error: LockFile C:\Users\cbour\.sciencefair\collection\docstore/LOCK: The process cannot access the file because it is being used by another process."
name:"OpenError"
stack:"OpenError: IO error: LockFile C:\Users\cbour\.sciencefair\collection\docstore/LOCK: The process cannot access the file because it is being used by another process.
    at C:\Program Files\ScienceFair\resources\app\node_modules\levelup\lib\levelup.js:119:34
    at C:\Program Files\ScienceFair\resources\app\node_modules\abstract-leveldown\abstract-leveldown.js:39:16"
type:"OpenError"
__proto__:Error
```

**Comment by blahah** [comment]
OK, my best guess here is that for some reason the require cache works differently on Windows than OSX/Linux, which is leading to the local collection leveldb being opened twice.

At the moment we depend on the behaviour that is standard in nodejs where if you require the same file twice in the same process, after the first time you just get an object cached in memory that was loaded at the first require. The only possible way that the local collection could be loaded twice is if this behaviour isn't working on Windows with electron.

I'll try making sure we just load the collection once, and store it in the app state, although I'm rather unhappy about doing that as it makes the state unserialisable, which in turn makes it harder to restore the app state on startup.

**Comment by blahah** [comment]
cc @cboursnell could you try https://github.com/codeforscience/sciencefair/releases/tag/v1.0.0-beta10 ?

**Comment by blahah** [comment]
This is now fixed on all windows instances I have access to. If anyone experiences it again please open a new issue.

Fix should work from beta11 onwards.
