### ISSUE TITLE
Spaces stripped from paper descriptions

### ISSUE THREAD

**Issue by gmaciocci** [codeforscience/sciencefair#72]
[Beta9, MacOS] All spaces seem to have been stripped from paper descriptions.

**Comment by blahah** [comment]
so they are... 

I haven't changed anything in [this view](https://github.com/codeforscience/sciencefair/blob/master/app/client/views/detail.js#L161), and the data arrives at the view with spaces.  

cc @yoshuawuyts - did anything change in the choo stack that might have been installed with only `^` flexibility in the deps, and would strip whitespace?

**Comment by blahah** [comment]
@pfrazee identified the source of the problem: https://github.com/shama/bel/issues/72

**Comment by blahah** [comment]
This has now been fixed - thanks @yoshuawuyts https://github.com/shama/bel/pull/74

Next beta of sciencefair will include the fix (deps updated in 19aa9f2)
