### ISSUE TITLE
[v1.0.1 macOS] reader scrollbar moves the whole app

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#89]
reported on IRC by @bcomnes
![screenshot](https://usercontent.irccloud-cdn.com/file/J1O13Zjj/scroller)

**Comment by bcomnes** [comment]
More data:

![screen shot 2017-06-25 at 12 39 08 pm](https://user-images.githubusercontent.com/166301/27519248-57dd098a-59a4-11e7-865f-b17aa9236ac6.png)

![screen shot 2017-06-25 at 12 39 18 pm](https://user-images.githubusercontent.com/166301/27519249-5b39131c-59a4-11e7-8550-78bdfde47d3e.png)
