### ISSUE TITLE
Highlight search term matches in result cards

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#9]

**Comment by meis** [comment]
I'll be working on that today :)

**Comment by blahah** [comment]
This was implemented by @meis in an early version (https://github.com/codeforscience/sciencefair/pull/28), but has been lost as the app was almost completely rewritten. Would be nice to merge that stuff back in - it was a useful feature.

**Comment by alvesjtiago** [comment]
Hi @blahah, I started working on a new version of this:

<img width="1111" alt="screen shot 2017-07-03 at 00 10 50" src="https://user-images.githubusercontent.com/407470/27774186-3d8b1154-5f84-11e7-9fed-d4d3581f8d9a.png">

What do you think?
However there are some articles that the search terms only appear on the detail. Should the words be highlighted there too?

I will continue working, refactoring some code and implementing the highlight for the authors as well. Hope to have a version to submit a pull request soon.

**Comment by blahah** [comment]
💯 👍  thank you! Looks just right.

I do think highlighting the search term in the detail view would be nice, but it's not crucial. It would work to have the title and author highlights in one PR, and add the detail highlighting later. Or all together is cool too :)

**Comment by alvesjtiago** [comment]
Great! Hope to have a PR ready with the author and title later today.
