### ISSUE TITLE
[v1.0.3 macOS] DMG installer window is ugly

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#98]
We are violating our own 'be beautiful' design principle with the macOS DMG:

![screen shot 2017-06-28 at 22 14 55](https://user-images.githubusercontent.com/836040/27655827-5e10b574-5c4f-11e7-8e03-636719339869.png)

We should design a nice background and layout for this.

**Comment by alvesjtiago** [comment]
Hi @blahah, worked on a quick version of the installer using the image from the website header and repositioned the icons (https://github.com/codeforscience/sciencefair/pull/116).

Let me know what you think 😊 hope to contribute much more to this project.

<img width="849" alt="screen shot 2017-06-30 at 18 51 47" src="https://user-images.githubusercontent.com/407470/27748316-e47bc73e-5dc6-11e7-8ea5-fff6ef30c3b6.png">

**Comment by blahah** [comment]
so much better - thanks @alvesjtiago 

> hope to contribute much more to this project

awesome!
